feat: provider json digest
superfaceai/ast-js pull request #84
Opened 2021-12-01 06:14 UTC by Jakub-Vacek

## Description

This PR adds optional parameters to provider.json digest security scheme. 

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTION_GUIDE** document.
- [x] I haven't repeated the code. (DRY)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-12-01 07:57 UTC, lukas-valenta requested changes

2021-12-01 07:57 UTC, lukas-valenta commented on src/interfaces/providerjson/providerjson.ts
> + * authorizationHeader is name of header containing authorization eq. Authorization
pls put the comments on the properties

2021-12-02 11:30 UTC, martinalbert approved these changes

2021-12-02 11:30 UTC, martinalbert commented on src/interfaces/providerjson/providerjson.ts
> +  authorizationHeader?: string | undefined;
```suggestion
  /**
   * Name of header containing challenge from the server eg. www-authenticate
   */
  challengeHeader?: string | undefined;
  /**
   * Name of header containing authorization eg. Authorization
   */
  authorizationHeader?: string | undefined;
```

2021-12-02 11:51 UTC, TheEdward162 approved these changes

2021-12-02 11:56 UTC, merged